# see https://github.com/ulisesbocchio/spring-boot-security-saml/blob/spring-boot-security-saml-parent-1.16/docs/properties/config-properties.md
saml:
  sso:
    default-success-url: /
    idp-selection-page-url: /idpSelection
    metadata-generator:
      entity-id: portal-saml
      request-signed: false
      want-assertion-signed: true
    logout:
      default-target-url: /
    idp:
      metadata-location: classpath:client-tailored-saml-idp-metadata.xml
    metadata-manager:
      refresh-check-interval: 0
    extended-metadata:
      idp-discovery-enabled: false
#    key-manager:
#      private-key-der-location: classpath:/localhost.key.der
#      public-key-pem-location: classpath:/localhost.cert

logging.level.root: INFO