spring:
  security:
    oauth2:
      client:
        registration:
          portal-oidc:
            client-id: portal-oidc
            client-secret: d614fed2-59cd-4942-b4bb-aa1c37442984
            client-name: My Portal
            provider: keycloak
            scope: openid
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://${DOCKER_HOST:localhost}:8180/auth/realms/sample

logging.level.root: INFO